CREATE TABLE APPS (
    CD_APP BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRICE FLOAT NOT NULL
);

CREATE TABLE CLIENTES (
    ID_CLIENTE BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE ASSINATURAS (
    ID_ASSINATURA BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_APP BIGINT NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    INICIO_VIGENCIA DATE NOT NULL,
    FIM_VIGENCIA DATE,
    CONSTRAINT FK_ASSINATURA_APP FOREIGN KEY (ID_APP) REFERENCES APPS(CD_APP),
    CONSTRAINT FK_ASSINATURA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PAGAMENTO (
    CD_PAGAMENTO BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_ASSINATURA BIGINT NOT NULL,
    VALOR_PAGO FLOAT NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    PROMOCAO VARCHAR(255),
    CONSTRAINT FK_PAGAMENTO_ASSINATURA FOREIGN KEY (ID_ASSINATURA) REFERENCES ASSINATURAS(ID_ASSINATURA)
);



