INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Alice', 'alice@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Bob', 'bob@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Charlie', 'charlie@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Diana', 'diana@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Edward', 'edward@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Fiona', 'fiona@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('George', 'george@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Hannah', 'hannah@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Isaac', 'isaac@example.com');
INSERT INTO CLIENTES (USERNAME, EMAIL) VALUES ('Julia', 'julia@example.com');

INSERT INTO APPS (NAME, PRICE) VALUES ('Spotify', 19.99);
INSERT INTO APPS (NAME, PRICE) VALUES ('Netflix', 39.99);
INSERT INTO APPS (NAME, PRICE) VALUES ('Amazon Prime', 25.99);
INSERT INTO APPS (NAME, PRICE) VALUES ('Disney+', 29.99);
INSERT INTO APPS (NAME, PRICE) VALUES ('HBO Max', 34.99);
